#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1



start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/BrfHeatControlModbusModbus
    procd_set_param respawn 3600 5 10  # Restart if it crashes: 1hr timeout, 5 retries, no delay
    procd_set_param stdout 1
    procd_set_param stderr 1
	procd_set_param pidfile /var/run/BrfHeatControlModbusModbus.pid
	procd_set_param file /etc/BrfHeatControlModbusModbus.json
    procd_close_instance
}



